// DEF_FUNC(name, priority, hasOneArg, string, stringLength, code)

DEF_FUNC(ASSIGN_OPERATION,  0, flse,  "=",      2, ;)
DEF_FUNC(ADD_OPERATION,     0, false, "+",      1, ;)
DEF_FUNC(SUB_OPERATION,     0, false, "-",      1, ;)
DEF_FUNC(MUL_OPERATION,     1, false, "*",      1, ;)
DEF_FUNC(DIV_OPERATION,     1, false, "/",      1, ;)
DEF_FUNC(POWER_OPERATION,   2, false, "^",      1, ;)
DEF_FUNC(SIN_OPERATION,     3, true,  "sin",    3, ;)
DEF_FUNC(COS_OPERATION,     3, true,  "cos",    3, ;)
DEF_FUNC(TAN_OPERATION,     3, true,  "tan",    3, ;)
DEF_FUNC(ARC_SIN_OPERATION, 3, true,  "arcsin", 6, ;)
DEF_FUNC(ARC_COS_OPERATION, 3, true,  "arccos", 6, ;)
DEF_FUNC(ARC_TAN_OPERATION, 3, true,  "arctan", 6, ;)
DEF_FUNC(EXP_OPERATION,     3, true,  "exp",    3, ;)
DEF_FUNC(LN_OPERATION,      3, true,  "ln",     2, ;)
