// DEF_FUNC(name, priority, hasOneArg, string, stringLength, code)

DEF_FUNC(ASSIGN_OPERATION,  0, false, "=",      1, (a) + (b))
DEF_FUNC(ADD_OPERATION,     0, false, "+",      1, (a) + (b))
DEF_FUNC(SUB_OPERATION,     0, false, "-",      1, (a) - (b))
DEF_FUNC(MUL_OPERATION,     1, false, "*",      1, (a) * (b))
DEF_FUNC(DIV_OPERATION,     1, false, "/",      1, (a) / (b))
DEF_FUNC(POWER_OPERATION,   2, false, "^",      1, pow(a, b))
DEF_FUNC(SIN_OPERATION,     3, true,  "sin",    3, sin(a))
DEF_FUNC(COS_OPERATION,     3, true,  "cos",    3, cos(a))
DEF_FUNC(TAN_OPERATION,     3, true,  "tan",    3, tan(a))
DEF_FUNC(ARC_SIN_OPERATION, 3, true,  "arcsin", 6, asin(a))
DEF_FUNC(ARC_COS_OPERATION, 3, true,  "arccos", 6, acos(a))
DEF_FUNC(ARC_TAN_OPERATION, 3, true,  "arctan", 6, atan(a))
DEF_FUNC(EXP_OPERATION,     3, true,  "exp",    3, exp(a))
DEF_FUNC(LN_OPERATION,      3, true,  "ln",     2, log(a))
